default:
    # Custom docker image: ubuntu:jammy with build dependencies preinstalled.
    image: linux-builder-ubuntu-jammy

    before_script:
        # Configure git to be able to push.
        - git config --global user.name "Tuxedo BOT"
        - git config --global user.email "tux@tuxedocomputers.com"
        - gpg --import $TUXEDO_BOT_GPG_PRIVATE_KEY

        # Setup author for dch.
        - export DEBFULLNAME="Tuxedo BOT"
        - export DEBEMAIL="tux@tuxedocomputers.com"

variables:
    # Create a fresh clone every time, instead of caching the last checkout of the repository. This
    # is required for a clean slate the way the auto-update script expects.
    GIT_STRATEGY: none

stages:
    # The update job is not run on the same commit as the build, and deploy jobs. It's included in this
    # explicit order here purely to make the CI script more readable.
    - update

update:
    stage: update

    script:
        - env
        - echo $SHELL
        - echo $0
        - echo $PATH
        - readlink /proc/$$/exe
        # GitLab CI checks out in a detached head state, correct this to be able to push.
        #- git checkout $CI_COMMIT_BRANCH

        # Run the logic determining the new version, update, and push the result.
        #- repo_list="$GETABIS_DOWNLOAD_URL" ./tuxedo-update-repository auto-update