#!/bin/bash

set -ex

MAINLINE_KERNEL_VERSION=5.11
UBUNTU_KERNEL_BRANCH=hwe-${MAINLINE_KERNEL_VERSION}

echo "===Starting version update.==="

SCRIPT=$(realpath "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
cd "$SCRIPTPATH"

echo "===Edit configuration.==="

if [ -d "debian.tuxedo-5.11" ]; then
    echo "Tuxedo configuration already exists."
    exit -1
fi

echo "DEBIAN=debian.tuxedo-5.11" > debian/debian.env
cp -r debian.hwe-5.11 debian.tuxedo-5.11

mv debian.tuxedo-5.11/config/amd64/config.flavour.generic debian.tuxedo-5.11/config/amd64/config.flavour.tuxedo
rm debian.tuxedo-5.11/config/amd64/config.flavour.lowlatency
rm -r debian.tuxedo-5.11/config/arm64 debian.tuxedo-5.11/config/armhf debian.tuxedo-5.11/config/ppc64el debian.tuxedo-5.11/config/s390x debian.tuxedo-5.11/config/x32
sed -i "s/'amd64-generic': 'n'/'amd64-generic': 'n', 'amd64-tuxedo': 'n'/" debian.tuxedo-5.11/config/annotations
sed -i "s/'amd64-generic': 'y'/'amd64-generic': 'y', 'amd64-tuxedo': 'y'/" debian.tuxedo-5.11/config/annotations
sed -i "s/'amd64-generic': 'm'/'amd64-generic': 'm', 'amd64-tuxedo': 'm'/" debian.tuxedo-5.11/config/annotations

rm debian.tuxedo-5.11/rules.d/arm64.mk debian.tuxedo-5.11/rules.d/armhf.mk debian.tuxedo-5.11/rules.d/i386.mk debian.tuxedo-5.11/rules.d/ppc64el.mk debian.tuxedo-5.11/rules.d/riscv64.mk debian.tuxedo-5.11/rules.d/s390x.mk debian.tuxedo-5.11/rules.d/x32.mk
sed -i 's/flavours	= generic lowlatency/flavours	= tuxedo/' debian.tuxedo-5.11/rules.d/amd64.mk

sed -i 's/archs="amd64 armhf arm64 ppc64el s390x"/archs="amd64"/' debian.tuxedo-5.11/etc/kernelconfig

mv debian.tuxedo-5.11/control.d/generic.inclusion-list debian.tuxedo-5.11/control.d/tuxedo.inclusion-list
mv debian.tuxedo-5.11/control.d/vars.generic debian.tuxedo-5.11/control.d/vars.tuxedo
rm debian.tuxedo-5.11/control.d/vars.generic-64k debian.tuxedo-5.11/control.d/vars.generic-lpae debian.tuxedo-5.11/control.d/vars.lowlatency
sed -i 's/arch="amd64 armhf arm64 ppc64el s390x"/arch="amd64"/' debian.tuxedo-5.11/control.d/vars.tuxedo
sed -i 's/supported="Generic"/supported="Tuxedo"/' debian.tuxedo-5.11/control.d/vars.tuxedo
sed -i 's/bootloader="grub-pc [amd64] | grub-efi-amd64 [amd64] | grub-efi-ia32 [amd64] | grub [amd64] | lilo [amd64] | flash-kernel [armhf arm64] | grub-ieee1275 [ppc64el]/bootloader="grub-pc [amd64] | grub-efi-amd64 [amd64] | grub-efi-ia32 [amd64] | grub [amd64] | lilo [amd64]/' debian.tuxedo-5.11/control.d/vars.tuxedo

rm debian.tuxedo-5.11/abi/*/amd64/lowlatency*
for i in debian.tuxedo-5.11/abi/*/amd64/generic*
do
    mv "$i" "${i/generic/tuxedo}"
done
rm -r debian.tuxedo-5.11/abi/*/arm64 debian.tuxedo-5.11/abi/*/armhf debian.tuxedo-5.11/abi/*/ppc64el debian.tuxedo-5.11/abi/*/s390x

rm -r debian.tuxedo-5.11/d-i/firmware/arm64 debian.tuxedo-5.11/d-i/firmware/armhf debian.tuxedo-5.11/d-i/firmware/i386 debian.tuxedo-5.11/d-i/firmware/powerpc debian.tuxedo-5.11/d-i/firmware/ppc64el debian.tuxedo-5.11/d-i/firmware/s390x
rm -r debian.tuxedo-5.11/d-i/modules/arm64 debian.tuxedo-5.11/d-i/modules/armhf debian.tuxedo-5.11/d-i/modules/i386 debian.tuxedo-5.11/d-i/modules/i386-virtual debian.tuxedo-5.11/d-i/modules/ppc64el debian.tuxedo-5.11/d-i/modules/s390x
rm debian.tuxedo-5.11/d-i/modules/*.powerpc debian.tuxedo-5.11/d-i/modules/*.s390x
echo -e "# arch\tversion\t\tflavour\t\tinstalledname\t\t\tsuffix\tbdep\namd64\t-\t\ttuxedo\t\t-\t\t\t\t-\t-\n\n# Ports\n# arch\tversion\t\tflavour\t\tinstalledname\t\t\tsuffix\tbdep" > debian.tuxedo-5.11/d-i/kernel-versions

sed -i 's/linux-hwe-5.11/linux-tuxedo-5.11/' Ubuntu.md
sed -i 's/generic, generic-64k, generic-lpae, lowlatency/tuxedo/' Ubuntu.md

rm debian.tuxedo-5.11/copyright
cp tuxedo-copyright debian.tuxedo-5.11/copyright

LANG=C fakeroot debian/rules clean
LANG=C fakeroot debian/rules updateconfigs

echo "===Update changelog.==="

BASE_VERSION_NUMBERS=($(grep -Pom2 "(?<=^linux-${UBUNTU_KERNEL_BRANCH} \().*(?=\))" debian.${UBUNTU_KERNEL_BRANCH}/changelog))
BASE_VERSION_NUMBER=${BASE_VERSION_NUMBERS[0]}
PREV_BASE_VERSION_NUMBER=${BASE_VERSION_NUMBERS[1]}

BASE_VERSION_ABI_AND_BUILD_LEVEL=${BASE_VERSION_NUMBER#*-}
BASE_VERSION_ABI_LEVEL=${BASE_VERSION_ABI_AND_BUILD_LEVEL%%.*}
TUX_VERSION_ABI_LEVEL=$((BASE_VERSION_ABI_LEVEL + 10000))
if [ $# -eq 1 ] && [[ $1 =~ ^[0-9]+$ ]]; then
    TUX_BUILD_NUMBER=$1
else
    TUX_BUILD_NUMBER=1
fi
TUX_VERSION_NUMBER=${BASE_VERSION_NUMBER%%-*}-${TUX_VERSION_ABI_LEVEL}.${BASE_VERSION_ABI_AND_BUILD_LEVEL#*.}tux${TUX_BUILD_NUMBER}

BASE_VERSION_PREFIX=Ubuntu-${UBUNTU_KERNEL_BRANCH}-
TUX_VERSION_PREFIX=Ubuntu-tuxedo-${MAINLINE_KERNEL_VERSION}-

BASE_VERSION_TAG=${BASE_VERSION_PREFIX}${BASE_VERSION_NUMBER//\~/_}
TUX_VERSION_TAG=${TUX_VERSION_PREFIX}${TUX_VERSION_NUMBER//\~/_}

# gbp dch has no way to specify a changelog in the non default location, so debian.tuxedo-*/changelog needs to be moved there, and back again.
mv debian.tuxedo-${MAINLINE_KERNEL_VERSION}/changelog debian/changelog
dch --newversion=$PREV_BASE_VERSION_NUMBER --force-bad-version --package=linux-tuxedo-${MAINLINE_KERNEL_VERSION} "Empty entry, required for the Ubuntu build scripts to not break"
dch --release ""
gbp dch --new-version=$TUX_VERSION_NUMBER --release --since=$BASE_VERSION_TAG --ignore-branch --spawn-editor=never
mv debian/changelog debian.tuxedo-${MAINLINE_KERNEL_VERSION}/changelog

echo "===Commit and tag.==="

git add debian/debian.env debian.tuxedo-${MAINLINE_KERNEL_VERSION}
git commit -s -m "TUXEDO: ${TUX_VERSION_PREFIX}${TUX_VERSION_NUMBER}"
git tag -s -m "${TUX_VERSION_PREFIX}${TUX_VERSION_NUMBER}" "${TUX_VERSION_TAG}"

echo "===Done.==="
