# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2024-2025 Werner Sembach wse@tuxedocomputers.com
#
# TUXEDO X86 Platform Specific Drivers
#

tuxedo_nb04_wmi_ab-y			:= wmi_ab.o
tuxedo_nb04_wmi_ab-y			+= wmi_util.o
obj-$(CONFIG_TUXEDO_NB04_WMI_AB)	+= tuxedo_nb04_wmi_ab.o

tuxedo_nb04_wmi_bs-y			:= wmi_bs.o
tuxedo_nb04_wmi_bs-y			+= wmi_util.o
obj-$(CONFIG_TUXEDO_NB04_WMI_BS)	+= tuxedo_nb04_wmi_bs.o

tuxedo_nb04_wmi_notify-y		:= wmi_notify.o
obj-$(CONFIG_TUXEDO_NB04_WMI_NOTIFY)	+= tuxedo_nb04_wmi_notify.o
