#!/bin/bash -eu

. debian/debian.env

sed -i "s/flavours	= generic/flavours	= tuxedo/" ${DEBIAN}/rules.d/amd64.mk
sed -i "s/# ARCH: amd64 arm64 armhf ppc64el riscv64 s390x/# ARCH: amd64/" ${DEBIAN}/config/annotations
sed -i "s/# FLAVOUR: amd64-generic arm64-generic arm64-generic-64k armhf-generic ppc64el-generic riscv64-generic s390x-generic/# FLAVOUR: amd64-tuxedo/" ${DEBIAN}/config/annotations
sed -i "s/Architecture: amd64 armhf arm64 i386 ppc64el riscv64 s390x/Architecture: amd64/" ${DEBIAN}/control.d/linux-libc-dev.stub
sed -i 's/arch="amd64 armhf arm64 ppc64el s390x"/arch="amd64"/' ${DEBIAN}/control.d/vars.tuxedo
sed -i 's/supported="Generic"/supported="Tuxedo"/' ${DEBIAN}/control.d/vars.tuxedo
sed -i 's/bootloader="grub-pc \[amd64\] | grub-efi-amd64 \[amd64\] | grub-efi-ia32 \[amd64\] | grub \[amd64\] | lilo \[amd64\] | flash-kernel \[armhf arm64\] | grub-efi-arm64 \[arm64\] | grub-efi-arm \[armhf\] | grub-ieee1275 \[ppc64el\]"/bootloader="grub-pc \[amd64\] | grub-efi-amd64 \[amd64\] | grub-efi-ia32 \[amd64\] | grub \[amd64\] | lilo \[amd64\]"/' ${DEBIAN}/control.d/vars.tuxedo
